### ISSUE TITLE
No static method current()Lio/opentelemetry/context/Context

### ISSUE THREAD

**Issue by yeling** [Azure-Samples/ms-identity-android-java#76]
### This issue is for a: (mark with an `x`)
```
- [x ] bug report
```

### Minimal steps to reproduce
>
1.   git clone https://github.com/Azure-Samples/ms-identity-android-java.git
2. ./gradlew build
3. adb install -r ./app/build/outputs/apk/external/debug/app-external-debug.a

### Any log messages given by the failure
>
No static method current()Lio/opentelemetry/context/Context; in class Lio/opentelemetry/context/Context; or its super classes (declaration of 'io.opentelemetry.context.Context' appears in /data/app/~~8CPrvi8BZW5Z9icWy5F3zg==/com.azuresamples.msalandroidapp-uMjEMjDR9Vu5SuNEj-XLDg==/base.apk)
                                                                                                    java.lang.NoSuchMethodError: No static method current()Lio/opentelemetry/context/Context; in class Lio/opentelemetry/context/Context; or its super classes (declaration of 'io.opentelemetry.context.Context' appears in /data/app/~~8CPrvi8BZW5Z9icWy5F3zg==/com.azuresamples.msalandroidapp-uMjEMjDR9Vu5SuNEj-XLDg==/base.apk)
                                                                                                    	at com.microsoft.identity.common.java.opentelemetry.OtelContextExtension.wrap(OtelContextExtension.java:57)
                                                                                                    	at com.microsoft.identity.common.java.controllers.CommandDispatcher.submitSilentReturningFuture(CommandDispatcher.java:341)
                                                                                                    	at com.microsoft.identity.common.java.controllers.CommandDispatcher.submitSilent(CommandDispatcher.java:181)
                                                                                                    	at com.microsoft.identity.client.SingleAccountPublicClientApplication$1.onMigrationFinished(SingleAccountPublicClientApplication.java:171)
                                                                                                    	at com.microsoft.identity.client.PublicClientApplication.performMigration(PublicClientApplication.java:2245)
                                                                                                    	at com.microsoft.identity.client.SingleAccountPublicClientApplication.getCurrentAccountAsyncInternal(SingleAccountPublicClientApplication.java:175)
                                                                                                    	at com.microsoft.identity.client.SingleAccountPublicClientApplication.getCurrentAccountAsync(SingleAccountPublicClientApplication.java:118)
                                                                                                    	at com.azuresamples.msalandroidapp.SingleAccountModeFragment.loadAccount(SingleAccountModeFragment.java:252)
                                                                                                    	at com.azuresamples.msalandroidapp.SingleAccountModeFragment.access$100(SingleAccountModeFragment.java:69)
                                                                                                    	at com.azuresamples.msalandroidapp.SingleAccountModeFragment$1.onCreated(SingleAccountModeFragment.java:106)
                                                                                                    	at com.microsoft.identity.client.PublicClientApplication$11.onCreated(PublicClientApplication.java:1031)
                                                                                                    	at com.microsoft.identity.client.PublicClientApplication$9.onTaskCompleted(PublicClientApplication.java:942)
                                                                                                    	at com.microsoft.identity.client.PublicClientApplication$9.onTaskCompleted(PublicClientApplication.java:930)
                                                                                                    	at com.microsoft.identity.common.java.controllers.CommandDispatcher.commandCallbackOnTaskCompleted(CommandDispatcher.java:649)
                                                                                                    	at com.microsoft.identity.common.java.controllers.CommandDispatcher.access$1000(CommandDispatcher.java:99)
                                                                                                    	at com.microsoft.identity.common.java.controllers.CommandDispatcher$4.run(CommandDispatcher.java:625)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:210)
                                                                                                    	at android.os.Looper.loop(Looper.java:299)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8252)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Apple M2
macOS Ventura 13.6.3 (22G436)

Android SDK 

### Versions
>

### Mention any other details that might be useful
If I run the app from the IDE(Android Studio), it run successfully, no such exception.
If I build the app using ./gradlew build , and install the app on my android phone.These error occurs.
![image](https://github.com/Azure-Samples/ms-identity-android-java/assets/6251064/10eaf096-dff0-4a58-aed7-c2b5fed79f9e)
![image](https://github.com/Azure-Samples/ms-identity-android-java/assets/6251064/46b16ffe-7318-4d25-a0fa-22b464aff787)

**Comment by yeling** [comment]
Finally , I find a solution. Change the minsdk from 21 to 24 in build.gradle file.

The root cause is masl sdk com.microsoft.identity.client depends on  io.opentelemetry:opentelemetry-bom:1.18.0。

And io.opentelemetry uses some java8 features, and it need support android api 21+。I run some tests, I need 24+.

https://github.com/open-telemetry/opentelemetry-java/blob/main/VERSIONING.md

![image](https://github.com/Azure-Samples/ms-identity-android-java/assets/6251064/7051d789-b6e0-4c72-a35c-a3e42a335110)
